# Wrangler configuration สำหรับ OpenNext Cloudflare adapter
main = ".open-next/worker.js"
name = "website-ui"
compatibility_date = "2025-01-04"
compatibility_flags = ["nodejs_compat"]

# Account ID จาก Cloudflare dashboard
account_id = "888725e55ac1543637e22d1c490c5d9c"

# Static Assets configuration
[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# Environment สำหรับ production
[env.production]
name = "website-ui"