import type { Metadata, Viewport } from "next";
import { Inter, IBM_Plex_Sans_Thai } from "next/font/google";
import { Theme } from "@/providers/theme";
import "@/styles/globals.css";
import { cx } from "@/utils/cx";

const inter = Inter({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-inter",
});

const ibmPlexSansThai = IBM_Plex_Sans_Thai({
    subsets: ["latin", "thai"],
    weight: ["100", "200", "300", "400", "500", "600", "700"],
    display: "swap",
    variable: "--font-ibm-plex-sans-thai",
});

export const metadata: Metadata = {
    title: "Starter kit — Untitled UI",
    description: "Generated by Untitled UI CLI",
};

export const viewport: Viewport = {
    themeColor: "#7f56d9",
    colorScheme: "light dark",
};

/**
 * Root Layout Component (fallback for pages without locale)
 * รองรับ font และ theme สำหรับหน้าที่ไม่ได้อยู่ใน locale routing
 */
export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="th" suppressHydrationWarning>
            <body 
                className={cx(inter.variable, ibmPlexSansThai.variable, "bg-primary antialiased")}
                suppressHydrationWarning={true}
            >
                <Theme>{children}</Theme>
            </body>
        </html>
    );
}
