import type { Metadata, Viewport } from "next";
import { Inter, IBM_Plex_Sans_Thai } from "next/font/google";
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { RouteProvider } from "@/providers/router-provider";
import { Theme } from "@/providers/theme";
import "@/styles/globals.css";
import { cx } from "@/utils/cx";

const inter = Inter({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-inter",
});

const ibmPlexSansThai = IBM_Plex_Sans_Thai({
    subsets: ["latin", "thai"],
    weight: ["100", "200", "300", "400", "500", "600", "700"],
    display: "swap",
    variable: "--font-ibm-plex-sans-thai",
});

export const metadata: Metadata = {
    title: "Starter kit — Untitled UI",
    description: "Generated by Untitled UI CLI",
};

export const viewport: Viewport = {
    themeColor: "#7f56d9",
    colorScheme: "light dark",
};

/**
 * Root Layout Component with i18n support
 * รองรับหลายภาษาและใช้ IBM Plex Sans Thai font
 */
export default async function LocaleLayout({
    children,
    params
}: {
    children: React.ReactNode;
    params: Promise<{ locale: string }>;
}) {
    // รอ params ก่อนใช้งาน (Next.js 15 requirement)
    const { locale } = await params;
    
    // โหลด messages สำหรับ locale ปัจจุบัน
    const messages = await getMessages({ locale });

    return (
        <html lang={locale} suppressHydrationWarning>
            <body 
                className={cx(inter.variable, ibmPlexSansThai.variable, "bg-primary antialiased")}
                suppressHydrationWarning={true}
            >
                <NextIntlClientProvider messages={messages}>
                    <RouteProvider>
                        <Theme>{children}</Theme>
                    </RouteProvider>
                </NextIntlClientProvider>
            </body>
        </html>
    );
}
